<a href="https://colab.research.google.com/github/anishsoni29/NIELIT-Colab/blob/main/Uttar_Pradesh_RAE_BARELI_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
x = pd.read_csv("sbm__uttar_pradesh__rae_bareli.csv")
x

,StateName,DistrictName,BlockName,GramPanchayatName,IHHLTotalAsPerDetails,IHHLTotalAch,Date
0,Uttar Pradesh,RAE BARELI,AMAWAN,ADAMPUR,303,303,5/19/2020 12:00:00 AM
1,Uttar Pradesh,RAE BARELI,AMAWAN,AMANWA,903,903,5/19/2020 12:00:00 AM
2,Uttar Pradesh,RAE BARELI,AMAWAN,ASHRAFABAD,274,274,5/19/2020 12:00:00 AM
3,Uttar Pradesh,RAE BARELI,AMAWAN,BAGHAI AHALWAR,312,312,5/19/2020 12:00:00 AM
4,Uttar Pradesh,RAE BARELI,AMAWAN,BAGHAIL1,406,406,5/19/2020 12:00:00 AM
...,...,...,...,...,...,...,...
984,Uttar Pradesh,RAE BARELI,UNCHAHAR,SAWAYYA RAJE,186,186,5/19/2020 12:00:00 AM
985,Uttar Pradesh,RAE BARELI,UNCHAHAR,SEMRI RANAPUR,166,166,5/19/2020 12:00:00 AM
986,Uttar Pradesh,RAE BARELI,UNCHAHAR,SHAHJADPUR MU.,399,399,5/19/2020 12:00:00 AM
987,Uttar Pradesh,RAE BARELI,UNCHAHAR,SUKRULLAPUR,265,265,5/19/2020 12:00:00 AM
988,Uttar Pradesh,RAE BARELI,UNCHAHAR,UNCHA HAR DEHAT,1229,1229,5/19/2020 12:00:00 AM

In [5]:
df = pd.DataFrame(x)
#Forming a Dataframe to tabulate the data and making it an object to perform operations upon
df

,StateName,DistrictName,BlockName,GramPanchayatName,IHHLTotalAsPerDetails,IHHLTotalAch,Date
0,Uttar Pradesh,RAE BARELI,AMAWAN,ADAMPUR,303,303,5/19/2020 12:00:00 AM
1,Uttar Pradesh,RAE BARELI,AMAWAN,AMANWA,903,903,5/19/2020 12:00:00 AM
2,Uttar Pradesh,RAE BARELI,AMAWAN,ASHRAFABAD,274,274,5/19/2020 12:00:00 AM
3,Uttar Pradesh,RAE BARELI,AMAWAN,BAGHAI AHALWAR,312,312,5/19/2020 12:00:00 AM
4,Uttar Pradesh,RAE BARELI,AMAWAN,BAGHAIL1,406,406,5/19/2020 12:00:00 AM
...,...,...,...,...,...,...,...
984,Uttar Pradesh,RAE BARELI,UNCHAHAR,SAWAYYA RAJE,186,186,5/19/2020 12:00:00 AM
985,Uttar Pradesh,RAE BARELI,UNCHAHAR,SEMRI RANAPUR,166,166,5/19/2020 12:00:00 AM
986,Uttar Pradesh,RAE BARELI,UNCHAHAR,SHAHJADPUR MU.,399,399,5/19/2020 12:00:00 AM
987,Uttar Pradesh,RAE BARELI,UNCHAHAR,SUKRULLAPUR,265,265,5/19/2020 12:00:00 AM
988,Uttar Pradesh,RAE BARELI,UNCHAHAR,UNCHA HAR DEHAT,1229,1229,5/19/2020 12:00:00 AM

In [6]:
df.head()

,StateName,DistrictName,BlockName,GramPanchayatName,IHHLTotalAsPerDetails,IHHLTotalAch,Date
0,Uttar Pradesh,RAE BARELI,AMAWAN,ADAMPUR,303,303,5/19/2020 12:00:00 AM
1,Uttar Pradesh,RAE BARELI,AMAWAN,AMANWA,903,903,5/19/2020 12:00:00 AM
2,Uttar Pradesh,RAE BARELI,AMAWAN,ASHRAFABAD,274,274,5/19/2020 12:00:00 AM
3,Uttar Pradesh,RAE BARELI,AMAWAN,BAGHAI AHALWAR,312,312,5/19/2020 12:00:00 AM
4,Uttar Pradesh,RAE BARELI,AMAWAN,BAGHAIL1,406,406,5/19/2020 12:00:00 AM

In [7]:
df.describe()

       IHHLTotalAsPerDetails  IHHLTotalAch
count             989.000000    989.000000
mean              386.360971    386.360971
std               247.839372    247.839372
min                 0.000000      0.000000
25%               233.000000    233.000000
50%               329.000000    329.000000
75%               476.000000    476.000000
max              2201.000000   2201.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 989 entries, 0 to 988
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   StateName              989 non-null    object
 1   DistrictName           989 non-null    object
 2   BlockName              989 non-null    object
 3   GramPanchayatName      989 non-null    object
 4   IHHLTotalAsPerDetails  989 non-null    int64
 5   IHHLTotalAch           989 non-null    int64
 6   Date                   989 non-null    object
dtypes: int64(2), object(5)
memory usage: 54.2+ KB